{
  "DurabilityWoodenHammer": 302,
  "DurabilityStoneHammer": 650,
  "DurabilityIronHammer": 1300,
  "DurabilityGoldHammer": 750,
  "DurabilityLapisHammer": 1100,
  "DurabilityRedstoneHammer": 1100,
  "DurabilityObsidianHammer": 2890,
  "DurabilityDiamondHammer": 8025,
  "DurabilityEmeraldHammer": 1500,
  "DurabilityNetheriteHammer": 13675,
  "radiusWoodenHammer": 1,
  "radiusStoneHammer": 1,
  "radiusIronHammer": 1,
  "radiusGoldHammer": 1,
  "radiusLapisHammer": 1,
  "radiusRedstoneHammer": 1,
  "radiusObsidianHammer": 2,
  "radiusDiamondHammer": 1,
  "radiusEmeraldHammer": 2,
  "radiusNetheriteHammer": 1,
  "DurabilityWoodenExcavator": 302,
  "DurabilityStoneExcavator": 650,
  "DurabilityIronExcavator": 1300,
  "DurabilityGoldExcavator": 750,
  "DurabilityLapisExcavator": 1100,
  "DurabilityRedstoneExcavator": 1100,
  "DurabilityObsidianExcavator": 2890,
  "DurabilityDiamondExcavator": 8025,
  "DurabilityEmeraldExcavator": 1500,
  "DurabilityNetheriteExcavator": 13675,
  "radiusWoodenExcavator": 1,
  "radiusStoneExcavator": 1,
  "radiusIronExcavator": 1,
  "radiusGoldExcavator": 1,
  "radiusLapisExcavator": 1,
  "radiusRedstoneExcavator": 1,
  "radiusObsidianExcavator": 2,
  "radiusDiamondExcavator": 1,
  "radiusEmeraldExcavator": 2,
  "radiusNetheriteExcavator": 1
}