#Config for Villager In A Bucket
#'enable-zombie-villager' should the ability to pick up Zombie Villagers in buckets be enabled. Default true
#
#Tue Apr 07 01:09:19 ICT 2026
enable-zombie-villager=true
